services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    env_file: '.env'
    restart: always
    shm_size: 128mb
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 1s
      timeout: 5s
      retries: 10
  gluwave:
    image: ghcr.io/kalhama/gluwave:latest
    ports:
      - '3000:3000'
    env_file: '.env'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
