services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    env_file: 'prod.env'
    restart: always
    shm_size: 128mb
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 1s
      timeout: 5s
      retries: 10
  gluwave:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        GITHUB_ID: ${GITHUB_ID}
        GITHUB_SECRET: ${GITHUB_SECRET}
        DATABASE_URL_UNPOOLED: ${DATABASE_URL_UNPOOLED}
        INTERVAL: ${INTERVAL}
    ports:
      - '3000:3000'
    env_file: 'prod.env'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
